### ISSUE TITLE
Arakoon_exc.Exception(4, "Not_found")

### ISSUE THREAD

**Issue by yongshengma** [openvstorage/arakoon#229]
If a key doesn't exist, `arakoon --get ` will throw an exception.  For example,

[root@node-03 ~]# arakoon -config /opt/OpenvStorage/config/arakoon_config.ini --get ovs/framework/scheduling/celery
Uncaught exception:
  
  Arakoon_exc.Exception(4, "Not_found")

Raised at file "src/core/lwt.ml", line 805, characters 16-23
Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Called from file "src/client/client_main.ml" (inlined), line 36, characters 12-27
Called from file "src/client/client_main.ml", line 87, characters 2-7
Called from file "src/main/arakoon.ml" (inlined), line 493, characters 13-50
Called from file "src/main/arakoon.ml", line 612, characters 7-23
Called from file "src/main/arakoon.ml", line 626, characters 9-16

It would be friendly if it reports sth like 'no key xxx defined', 'empty value' or exits silently instead of throwing an exception as above.

**Comment by toolslive** [comment]
You know the key so there's no value in repeating it. The value, if it exists is printed on `stdout`, while any error messages are printed on `stderr`.
You can use the return code of the process, and you can reroute `stderror` if you don't like the message.

```
# XXX does not exist
$ arakoon --get XXX -config $config 2> /dev/null
$ echo $?
2
```

Since you seem to be an OVS user, there's a full blown arakoon client available in the ovs shell
for python scripting
